import { Cat, Coffee, Flag, Hand, Lightbulb, Plane, Smile, Volleyball } from "lucide-react";
import type { EmojiCategory } from "../types/emoji";

/**
 * A curated set, not the whole Unicode block, and that is the decision.
 *
 * The full list is around 1,900 emoji with a data file to match, and shipping
 * it would mean either a dependency that arrives with its own stylesheet — and
 * therefore its own look, in an app whose whole point is one declared look — or
 * a megabyte of table nobody scrolls past the first screen of. What is here is
 * the couple of hundred people actually reach for, which is also the number
 * that stays browsable without a virtualised grid.
 *
 * `keywords` carries the *English* words to search by, plus a few unaccented
 * Vietnamese ones where the obvious search term differs — `cuoi` for a laugh,
 * `tim` for a heart. Unaccented on purpose: it is what gets typed, the same
 * reasoning the phase 20 message search rests on.
 */
export const EMOJI_CATEGORIES: EmojiCategory[] = [
	{
		id: "smileys",
		label: "Smileys",
		Icon: Smile,
		emoji: [
			{ char: "😀", keywords: "grin smile happy cuoi" },
			{ char: "😃", keywords: "smile happy joy cuoi" },
			{ char: "😄", keywords: "smile happy laugh cuoi" },
			{ char: "😁", keywords: "beam grin cuoi" },
			{ char: "😆", keywords: "laugh squint cuoi" },
			{ char: "😅", keywords: "sweat laugh relief cuoi" },
			{ char: "🤣", keywords: "rofl rolling laugh cuoi" },
			{ char: "😂", keywords: "joy tears laugh cuoi" },
			{ char: "🙂", keywords: "slight smile cuoi" },
			{ char: "🙃", keywords: "upside down silly" },
			{ char: "😉", keywords: "wink nhay mat" },
			{ char: "😊", keywords: "blush smile shy" },
			{ char: "😇", keywords: "innocent halo angel" },
			{ char: "🥰", keywords: "love hearts adore yeu" },
			{ char: "😍", keywords: "heart eyes love yeu" },
			{ char: "😘", keywords: "kiss blow hon" },
			{ char: "😗", keywords: "kiss hon" },
			{ char: "😋", keywords: "yum tasty ngon" },
			{ char: "😛", keywords: "tongue playful" },
			{ char: "😜", keywords: "wink tongue silly" },
			{ char: "🤪", keywords: "zany goofy crazy" },
			{ char: "🤨", keywords: "eyebrow suspicious doubt" },
			{ char: "🧐", keywords: "monocle inspect" },
			{ char: "🤓", keywords: "nerd glasses" },
			{ char: "😎", keywords: "cool sunglasses ngau" },
			{ char: "🥳", keywords: "party celebrate an mung" },
			{ char: "😏", keywords: "smirk sly" },
			{ char: "😒", keywords: "unamused meh" },
			{ char: "😞", keywords: "sad disappointed buon" },
			{ char: "😔", keywords: "pensive sad buon" },
			{ char: "😟", keywords: "worried lo" },
			{ char: "😕", keywords: "confused" },
			{ char: "🙁", keywords: "frown sad buon" },
			{ char: "😣", keywords: "persevere struggle" },
			{ char: "😖", keywords: "confounded" },
			{ char: "😫", keywords: "tired met" },
			{ char: "😩", keywords: "weary met" },
			{ char: "🥺", keywords: "pleading puppy beg xin" },
			{ char: "😢", keywords: "cry tear khoc buon" },
			{ char: "😭", keywords: "sob cry loud khoc" },
			{ char: "😤", keywords: "triumph huff" },
			{ char: "😠", keywords: "angry mad gian" },
			{ char: "😡", keywords: "rage furious gian" },
			{ char: "🤯", keywords: "mind blown shock" },
			{ char: "😳", keywords: "flushed embarrassed" },
			{ char: "🥵", keywords: "hot heat nong" },
			{ char: "🥶", keywords: "cold freeze lanh" },
			{ char: "😱", keywords: "scream fear so" },
			{ char: "😨", keywords: "fearful scared so" },
			{ char: "😰", keywords: "anxious sweat lo" },
			{ char: "😥", keywords: "sad relief" },
			{ char: "🤔", keywords: "thinking hmm nghi" },
			{ char: "🤫", keywords: "shush quiet im" },
			{ char: "🤭", keywords: "oops giggle" },
			{ char: "😶", keywords: "no mouth speechless" },
			{ char: "😐", keywords: "neutral blank" },
			{ char: "😑", keywords: "expressionless" },
			{ char: "😬", keywords: "grimace awkward" },
			{ char: "🙄", keywords: "roll eyes" },
			{ char: "😴", keywords: "sleep zzz ngu" },
			{ char: "🤤", keywords: "drool" },
			{ char: "🤢", keywords: "nauseated sick" },
			{ char: "🤮", keywords: "vomit sick" },
			{ char: "🤧", keywords: "sneeze sick om" },
			{ char: "😷", keywords: "mask sick om" },
			{ char: "🤒", keywords: "thermometer sick om" },
			{ char: "🥱", keywords: "yawn tired buon ngu" },
			{ char: "😵", keywords: "dizzy" },
			{ char: "🤠", keywords: "cowboy" },
			{ char: "👻", keywords: "ghost spooky ma" },
			{ char: "💀", keywords: "skull dead" },
			{ char: "🤡", keywords: "clown" },
			{ char: "💩", keywords: "poop" },
			{ char: "🙈", keywords: "see no evil monkey" },
			{ char: "🙉", keywords: "hear no evil monkey" },
			{ char: "🙊", keywords: "speak no evil monkey" },
		],
	},
	{
		id: "gestures",
		label: "People",
		Icon: Hand,
		emoji: [
			{ char: "👍", keywords: "thumbs up like ok dong y" },
			{ char: "👎", keywords: "thumbs down dislike" },
			{ char: "👌", keywords: "ok perfect" },
			{ char: "🤌", keywords: "pinched fingers" },
			{ char: "✌️", keywords: "peace victory" },
			{ char: "🤞", keywords: "fingers crossed luck" },
			{ char: "🤝", keywords: "handshake deal" },
			{ char: "👏", keywords: "clap applause vo tay" },
			{ char: "🙌", keywords: "raise hands celebrate" },
			{ char: "🙏", keywords: "pray thanks please cam on" },
			{ char: "💪", keywords: "muscle strong manh" },
			{ char: "👋", keywords: "wave hello hi bye chao" },
			{ char: "🤙", keywords: "call me shaka" },
			{ char: "☝️", keywords: "point up" },
			{ char: "👇", keywords: "point down" },
			{ char: "👉", keywords: "point right" },
			{ char: "👈", keywords: "point left" },
			{ char: "✍️", keywords: "writing hand" },
			{ char: "🫶", keywords: "heart hands love" },
			{ char: "👀", keywords: "eyes look watch nhin" },
			{ char: "🧠", keywords: "brain" },
			{ char: "👶", keywords: "baby" },
			{ char: "🧑", keywords: "person" },
			{ char: "👨", keywords: "man" },
			{ char: "👩", keywords: "woman" },
			{ char: "👴", keywords: "old man" },
			{ char: "👵", keywords: "old woman" },
			{ char: "🧑‍💻", keywords: "developer coding lap trinh" },
			{ char: "🕺", keywords: "dance man" },
			{ char: "💃", keywords: "dance woman" },
			{ char: "🚶", keywords: "walking" },
			{ char: "🏃", keywords: "running chay" },
		],
	},
	{
		id: "hearts",
		label: "Hearts",
		Icon: Lightbulb,
		emoji: [
			{ char: "❤️", keywords: "red heart love tim yeu" },
			{ char: "🧡", keywords: "orange heart tim" },
			{ char: "💛", keywords: "yellow heart tim" },
			{ char: "💚", keywords: "green heart tim" },
			{ char: "💙", keywords: "blue heart tim" },
			{ char: "💜", keywords: "purple heart tim" },
			{ char: "🖤", keywords: "black heart tim" },
			{ char: "🤍", keywords: "white heart tim" },
			{ char: "💖", keywords: "sparkling heart tim" },
			{ char: "💗", keywords: "growing heart tim" },
			{ char: "💕", keywords: "two hearts love tim" },
			{ char: "💔", keywords: "broken heart tan vo" },
			{ char: "❣️", keywords: "heart exclamation" },
			{ char: "💯", keywords: "hundred perfect score" },
			{ char: "✨", keywords: "sparkles shiny" },
			{ char: "⭐", keywords: "star sao" },
			{ char: "🌟", keywords: "glowing star sao" },
			{ char: "🔥", keywords: "fire lit hot chay" },
			{ char: "💥", keywords: "boom collision" },
			{ char: "⚡", keywords: "lightning zap" },
			{ char: "💫", keywords: "dizzy star" },
			{ char: "🎉", keywords: "party popper celebrate an mung" },
			{ char: "🎊", keywords: "confetti celebrate" },
			{ char: "🎂", keywords: "birthday cake sinh nhat" },
			{ char: "🎁", keywords: "gift present qua" },
			{ char: "🏆", keywords: "trophy win cup" },
			{ char: "🥇", keywords: "gold medal first" },
			{ char: "✅", keywords: "check done tick xong" },
			{ char: "❌", keywords: "cross wrong no sai" },
			{ char: "❓", keywords: "question hoi" },
			{ char: "❗", keywords: "exclamation important" },
			{ char: "⚠️", keywords: "warning caution canh bao" },
		],
	},
	{
		id: "animals",
		label: "Animals",
		Icon: Cat,
		emoji: [
			{ char: "🐶", keywords: "dog puppy cho" },
			{ char: "🐱", keywords: "cat kitten meo" },
			{ char: "🐭", keywords: "mouse chuot" },
			{ char: "🐹", keywords: "hamster" },
			{ char: "🐰", keywords: "rabbit bunny tho" },
			{ char: "🦊", keywords: "fox cao" },
			{ char: "🐻", keywords: "bear gau" },
			{ char: "🐼", keywords: "panda gau truc" },
			{ char: "🐨", keywords: "koala" },
			{ char: "🐯", keywords: "tiger ho" },
			{ char: "🦁", keywords: "lion su tu" },
			{ char: "🐮", keywords: "cow bo" },
			{ char: "🐷", keywords: "pig lon heo" },
			{ char: "🐸", keywords: "frog ech" },
			{ char: "🐵", keywords: "monkey khi" },
			{ char: "🐔", keywords: "chicken ga" },
			{ char: "🐧", keywords: "penguin" },
			{ char: "🐦", keywords: "bird chim" },
			{ char: "🦆", keywords: "duck vit" },
			{ char: "🦉", keywords: "owl cu" },
			{ char: "🐝", keywords: "bee ong" },
			{ char: "🦋", keywords: "butterfly buom" },
			{ char: "🐟", keywords: "fish ca" },
			{ char: "🐬", keywords: "dolphin ca heo" },
			{ char: "🐳", keywords: "whale ca voi" },
			{ char: "🐢", keywords: "turtle rua" },
			{ char: "🐍", keywords: "snake ran" },
			{ char: "🌸", keywords: "cherry blossom flower hoa" },
			{ char: "🌹", keywords: "rose flower hoa hong" },
			{ char: "🌻", keywords: "sunflower hoa" },
			{ char: "🌴", keywords: "palm tree cay" },
			{ char: "🌵", keywords: "cactus xuong rong" },
			{ char: "🍀", keywords: "clover luck may man" },
			{ char: "🌙", keywords: "moon trang" },
			{ char: "☀️", keywords: "sun nang" },
			{ char: "🌈", keywords: "rainbow cau vong" },
		],
	},
	{
		id: "food",
		label: "Food",
		Icon: Coffee,
		emoji: [
			{ char: "🍎", keywords: "apple tao" },
			{ char: "🍌", keywords: "banana chuoi" },
			{ char: "🍇", keywords: "grapes nho" },
			{ char: "🍉", keywords: "watermelon dua hau" },
			{ char: "🍓", keywords: "strawberry dau" },
			{ char: "🥭", keywords: "mango xoai" },
			{ char: "🍑", keywords: "peach dao" },
			{ char: "🥥", keywords: "coconut dua" },
			{ char: "🍍", keywords: "pineapple dua" },
			{ char: "🥑", keywords: "avocado bo" },
			{ char: "🍞", keywords: "bread banh mi" },
			{ char: "🥖", keywords: "baguette banh mi" },
			{ char: "🧀", keywords: "cheese pho mai" },
			{ char: "🍔", keywords: "burger hamburger" },
			{ char: "🍟", keywords: "fries khoai tay" },
			{ char: "🍕", keywords: "pizza" },
			{ char: "🌭", keywords: "hot dog" },
			{ char: "🌮", keywords: "taco" },
			{ char: "🍜", keywords: "noodles ramen pho mi" },
			{ char: "🍚", keywords: "rice com" },
			{ char: "🍣", keywords: "sushi" },
			{ char: "🍤", keywords: "shrimp tom" },
			{ char: "🥟", keywords: "dumpling banh bao" },
			{ char: "🍦", keywords: "ice cream kem" },
			{ char: "🍩", keywords: "donut banh" },
			{ char: "🍪", keywords: "cookie banh quy" },
			{ char: "🍫", keywords: "chocolate socola" },
			{ char: "☕", keywords: "coffee ca phe" },
			{ char: "🍵", keywords: "tea tra" },
			{ char: "🧋", keywords: "bubble tea tra sua" },
			{ char: "🍺", keywords: "beer bia" },
			{ char: "🍻", keywords: "cheers beers nhau" },
			{ char: "🥂", keywords: "cheers champagne" },
			{ char: "🍷", keywords: "wine ruou" },
			{ char: "🥤", keywords: "drink cup nuoc" },
			{ char: "💧", keywords: "water drop nuoc" },
		],
	},
	{
		id: "activity",
		label: "Activity",
		Icon: Volleyball,
		emoji: [
			{ char: "⚽", keywords: "football soccer bong da" },
			{ char: "🏀", keywords: "basketball bong ro" },
			{ char: "🏈", keywords: "american football" },
			{ char: "🎾", keywords: "tennis" },
			{ char: "🏐", keywords: "volleyball bong chuyen" },
			{ char: "🏓", keywords: "ping pong bong ban" },
			{ char: "🏸", keywords: "badminton cau long" },
			{ char: "🥊", keywords: "boxing" },
			{ char: "🏊", keywords: "swimming boi" },
			{ char: "🚴", keywords: "cycling bike xe dap" },
			{ char: "🧘", keywords: "yoga meditation thien" },
			{ char: "🎮", keywords: "game controller choi game" },
			{ char: "🎧", keywords: "headphones music tai nghe" },
			{ char: "🎵", keywords: "music note nhac" },
			{ char: "🎸", keywords: "guitar dan" },
			{ char: "🎤", keywords: "microphone sing hat" },
			{ char: "🎬", keywords: "movie clapper phim" },
			{ char: "📷", keywords: "camera photo anh" },
			{ char: "📚", keywords: "books study hoc sach" },
			{ char: "✏️", keywords: "pencil write viet" },
			{ char: "💡", keywords: "idea lightbulb y tuong" },
			{ char: "🔑", keywords: "key chia khoa" },
			{ char: "🔒", keywords: "lock secure khoa" },
			{ char: "💰", keywords: "money bag tien" },
			{ char: "💳", keywords: "credit card the" },
			{ char: "🛒", keywords: "cart shopping mua" },
			{ char: "🎯", keywords: "target dart muc tieu" },
			{ char: "🧩", keywords: "puzzle piece" },
		],
	},
	{
		id: "objects",
		label: "Work",
		Icon: Plane,
		emoji: [
			{ char: "💻", keywords: "laptop computer may tinh" },
			{ char: "🖥️", keywords: "desktop monitor man hinh" },
			{ char: "⌨️", keywords: "keyboard ban phim" },
			{ char: "🖱️", keywords: "mouse chuot" },
			{ char: "📱", keywords: "phone mobile dien thoai" },
			{ char: "☎️", keywords: "telephone call goi" },
			{ char: "📧", keywords: "email mail thu" },
			{ char: "📅", keywords: "calendar date lich" },
			{ char: "⏰", keywords: "alarm clock time gio" },
			{ char: "⏳", keywords: "hourglass waiting cho" },
			{ char: "📈", keywords: "chart up growth tang" },
			{ char: "📉", keywords: "chart down giam" },
			{ char: "📊", keywords: "bar chart bieu do" },
			{ char: "📝", keywords: "memo note ghi chu" },
			{ char: "📌", keywords: "pin ghim" },
			{ char: "📎", keywords: "paperclip attach" },
			{ char: "🗑️", keywords: "trash delete xoa" },
			{ char: "🔍", keywords: "search magnify tim" },
			{ char: "🔔", keywords: "bell notification chuong" },
			{ char: "🚀", keywords: "rocket launch ship" },
			{ char: "✈️", keywords: "airplane flight may bay" },
			{ char: "🚗", keywords: "car o to xe" },
			{ char: "🏠", keywords: "house home nha" },
			{ char: "🏢", keywords: "office building cong ty" },
			{ char: "🌍", keywords: "earth world the gioi" },
			{ char: "🛠️", keywords: "tools fix sua" },
			{ char: "🐛", keywords: "bug loi" },
			{ char: "☑️", keywords: "checkbox done xong" },
		],
	},
	{
		id: "symbols",
		label: "Symbols",
		Icon: Flag,
		emoji: [
			{ char: "🇻🇳", keywords: "vietnam flag co viet nam" },
			{ char: "🏁", keywords: "finish flag checkered" },
			{ char: "🚩", keywords: "red flag" },
			{ char: "🆗", keywords: "ok button" },
			{ char: "🆕", keywords: "new" },
			{ char: "🔝", keywords: "top up" },
			{ char: "🔄", keywords: "refresh repeat lap lai" },
			{ char: "▶️", keywords: "play start" },
			{ char: "⏸️", keywords: "pause dung" },
			{ char: "⏹️", keywords: "stop" },
			{ char: "🔊", keywords: "loud speaker am thanh" },
			{ char: "🔇", keywords: "mute silent tat tieng" },
			{ char: "➕", keywords: "plus add them" },
			{ char: "➖", keywords: "minus subtract bot" },
			{ char: "♻️", keywords: "recycle" },
			{ char: "💤", keywords: "zzz sleep ngu" },
		],
	},
];
